var searchData=
[
  ['cache_20functions_0',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['calculation_1',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['calculation_20of_20prediv_20for_201sec_20timebase_2',['Automatic calculation of prediv for 1sec timebase',['../group___r_t_c___automatic___prediv__1___second.html',1,'']]],
  ['call_20addressing_20mode_3',['I2C general call addressing mode',['../group___i2_c__general__call__addressing__mode.html',1,'']]],
  ['callbacks_20functions_4',['Callbacks functions',['../group___t_i_m_ex___exported___functions___group6.html',1,'Extended Callbacks functions'],['../group___t_i_m___exported___functions___group9.html',1,'TIM Callbacks functions']]],
  ['can_5',['CAN',['../group___c_a_n.html',1,'']]],
  ['can_20aliased_20defines_20maintained_20for_20legacy_20purpose_6',['HAL CAN Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_a_n___aliased___defines.html',1,'']]],
  ['capture_20compare_20channel_20state_7',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['capture_20functions_8',['TIM Input Capture functions',['../group___t_i_m___exported___functions___group4.html',1,'']]],
  ['capture_20polarity_9',['TIM Input Capture Polarity',['../group___t_i_m___input___capture___polarity.html',1,'']]],
  ['capture_20prescaler_10',['TIM Input Capture Prescaler',['../group___t_i_m___input___capture___prescaler.html',1,'']]],
  ['capture_20selection_11',['TIM Input Capture Selection',['../group___t_i_m___input___capture___selection.html',1,'']]],
  ['cec_20aliased_20defines_20maintained_20for_20legacy_20purpose_12',['HAL CEC Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_e_c___aliased___defines.html',1,'']]],
  ['channel_13',['TIM Channel',['../group___t_i_m___channel.html',1,'']]],
  ['channel_20polarity_14',['TIM Input Channel polarity',['../group___t_i_m___input___channel___polarity.html',1,'']]],
  ['channel_20state_15',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['channels_16',['channels',['../group___a_d_c__channels.html',1,'ADC channels'],['../group___a_d_c__sampling__times__all__channels.html',1,'ADC sampling times all channels']]],
  ['check_20enable_20list_17',['Check Enable list',['../group___v_l53_l0_x___check_enable__group.html',1,'']]],
  ['check_20input_20parameters_18',['check input parameters',['../group___i2_c___i_s___r_t_c___definitions.html',1,'I2C Private macros to check input parameters'],['../group___r_t_c_ex___i_s___r_t_c___definitions.html',1,'Private macros to check input parameters']]],
  ['clarke_20transform_19',['Clarke Transform',['../group__clarke.html',1,'Vector Clarke Transform'],['../group__inv__clarke.html',1,'Vector Inverse Clarke Transform']]],
  ['clear_20input_20polarity_20',['TIM Clear Input Polarity',['../group___t_i_m___clear_input___polarity.html',1,'']]],
  ['clear_20input_20prescaler_21',['TIM Clear Input Prescaler',['../group___t_i_m___clear_input___prescaler.html',1,'']]],
  ['clear_20input_20source_22',['TIM Clear Input Source',['../group___t_i_m___clear_input___source.html',1,'']]],
  ['clock_23',['USART Clock',['../group___u_s_a_r_t___clock.html',1,'']]],
  ['clock_20config_24',['RCC Extended MCOx Clock Config',['../group___r_c_c_ex___m_c_ox___clock___config.html',1,'']]],
  ['clock_20configuration_25',['RCC RTC Clock Configuration',['../group___r_c_c___r_t_c___clock___configuration.html',1,'']]],
  ['clock_20division_26',['TIM Clock Division',['../group___t_i_m___clock_division.html',1,'']]],
  ['clock_20enable_20disable_27',['Clock Enable Disable',['../group___r_c_c___a_p_b1___clock___enable___disable.html',1,'APB1 Clock Enable Disable'],['../group___r_c_c_ex___a_p_b1___clock___enable___disable.html',1,'APB1 Clock Enable Disable'],['../group___r_c_c___a_p_b2___clock___enable___disable.html',1,'APB2 Clock Enable Disable'],['../group___r_c_c_ex___a_p_b2___clock___enable___disable.html',1,'APB2 Clock Enable Disable'],['../group___r_c_c___peripheral___clock___enable___disable.html',1,'Peripheral Clock Enable Disable'],['../group___r_c_c_ex___peripheral___clock___enable___disable.html',1,'Peripheral Clock Enable Disable']]],
  ['clock_20enable_20disable_20status_28',['Clock Enable Disable Status',['../group___r_c_c___a_h_b___peripheral___clock___enable___disable___status.html',1,'AHB Peripheral Clock Enable Disable Status'],['../group___r_c_c_ex___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enable Disable Status'],['../group___r_c_c___a_p_b1___peripheral___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enable Disable Status'],['../group___r_c_c_ex___a_p_b1___peripheral___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enable Disable Status'],['../group___r_c_c___a_p_b2___peripheral___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enable Disable Status'],['../group___r_c_c_ex___a_p_b2___peripheral___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enable Disable Status']]],
  ['clock_20phase_29',['Clock Phase',['../group___s_m_a_r_t_c_a_r_d___clock___phase.html',1,'SMARTCARD Clock Phase'],['../group___s_p_i___clock___phase.html',1,'SPI Clock Phase'],['../group___u_s_a_r_t___clock___phase.html',1,'USART Clock Phase']]],
  ['clock_20polarity_30',['Clock Polarity',['../group___s_m_a_r_t_c_a_r_d___clock___polarity.html',1,'SMARTCARD Clock Polarity'],['../group___s_p_i___clock___polarity.html',1,'SPI Clock Polarity'],['../group___t_i_m___clock___polarity.html',1,'TIM Clock Polarity'],['../group___u_s_a_r_t___clock___polarity.html',1,'USART Clock Polarity']]],
  ['clock_20prescaler_31',['Clock Prescaler',['../group___r_c_c___m_c_ox___clock___prescaler.html',1,'MCO Clock Prescaler'],['../group___t_i_m___clock___prescaler.html',1,'TIM Clock Prescaler']]],
  ['clock_20selection_32',['Periph Clock Selection',['../group___r_c_c_ex___periph___clock___selection.html',1,'']]],
  ['clock_20source_33',['Clock Source',['../group___r_c_c___a_h_b___clock___source.html',1,'AHB Clock Source'],['../group___r_c_c___a_p_b1___a_p_b2___clock___source.html',1,'APB1 APB2 Clock Source']]],
  ['clock_20source_34',['CORTEX _SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['clock_20source_35',['Get Clock source',['../group___r_c_c___get___clock__source.html',1,'']]],
  ['clock_20source_36',['Clock Source',['../group___r_c_c_ex___m_c_o1___clock___source.html',1,'MCO1 Clock Source'],['../group___r_c_c___p_l_l___clock___source.html',1,'PLL Clock Source'],['../group___r_c_c___r_t_c___clock___source.html',1,'RTC Clock Source'],['../group___r_c_c___system___clock___source.html',1,'System Clock Source'],['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'SYSTICK Clock Source'],['../group___t_i_m___clock___source.html',1,'TIM Clock Source']]],
  ['clock_20source_20status_37',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['clock_20type_38',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['cmsis_39',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_40',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_41',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_42',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_43',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['code_44',['Code',['../group___a_d_c___error___code.html',1,'ADC Error Code'],['../group___d_m_a___error___code.html',1,'DMA Error Code'],['../group___i2_c___error___code.html',1,'I2C Error Code'],['../group___i_r_d_a___error___code.html',1,'IRDA Error Code']]],
  ['code_45',['MSP and User specific code',['../group___m_s_p__implement.html',1,'']]],
  ['code_46',['Code',['../group___s_m_a_r_t_c_a_r_d___error___code.html',1,'SMARTCARD Error Code'],['../group___s_p_i___error___code.html',1,'SPI Error Code'],['../group___u_a_r_t___error___code.html',1,'UART Error Code'],['../group___u_s_a_r_t___error___code.html',1,'USART Error Code']]],
  ['code_20returned_20by_20api_47',['Error and Warning code returned by API',['../group___v_l53_l0_x__define___error__group.html',1,'']]],
  ['codes_48',['FLASH Error Codes',['../group___f_l_a_s_h___error___codes.html',1,'']]],
  ['common_49',['Common',['../group___common.html',1,'']]],
  ['common_50',['COMMON',['../group___c_o_m_m_o_n.html',1,'']]],
  ['common_20register_51',['Common register',['../group___common__register__group___w5100.html',1,'']]],
  ['common_20register_20access_20functions_52',['Common register access functions',['../group___common__register__access__function___w5100.html',1,'']]],
  ['common_20to_20all_20stm32_53',['MSP Common to all STM32',['../group___m_s_p__implement__common.html',1,'']]],
  ['commutation_20source_54',['TIM Commutation Source',['../group___t_i_m___commutation___source.html',1,'']]],
  ['comp_20aliased_20defines_20maintained_20for_20legacy_20purpose_55',['HAL COMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_o_m_p___aliased___defines.html',1,'']]],
  ['comp_20aliased_20macros_20maintained_20for_20legacy_20purpose_56',['HAL COMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___c_o_m_p___aliased___macros.html',1,'']]],
  ['compare_20and_20pwm_20modes_57',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['compare_20channel_20state_58',['TIM Capture/Compare Channel State',['../group___channel___c_c___state.html',1,'']]],
  ['compare_20functions_59',['Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['compare_20idle_20state_60',['Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['compare_20polarity_61',['Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['compare_20state_62',['Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['compatibility_20purpose_63',['LL FMC Aliased Defines maintained for compatibility purpose',['../group___l_l___f_m_c___aliased___defines.html',1,'']]],
  ['complementary_20one_20pulse_20functions_64',['Extended Timer Complementary One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'']]],
  ['complementary_20output_20compare_20functions_65',['Extended Timer Complementary Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'']]],
  ['complementary_20output_20compare_20idle_20state_66',['TIM Complementary Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'']]],
  ['complementary_20output_20compare_20polarity_67',['TIM Complementary Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'']]],
  ['complementary_20output_20compare_20state_68',['TIM Complementary Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'']]],
  ['complementary_20pwm_20functions_69',['Extended Timer Complementary PWM functions',['../group___t_i_m_ex___exported___functions___group3.html',1,'']]],
  ['complex_20math_20functions_70',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['component_71',['COMPONENT',['../group___c_o_m_p_o_n_e_n_t.html',1,'']]],
  ['component_20public_20types_72',['COMPONENT Public Types',['../group___c_o_m_p_o_n_e_n_t___public___types.html',1,'']]],
  ['components_73',['Components',['../group___components.html',1,'']]],
  ['components_74',['COMPONENTS',['../group___c_o_m_p_o_n_e_n_t_s.html',1,'']]],
  ['config_75',['Config',['../group___r_c_c___h_s_e___config.html',1,'HSE Config'],['../group___r_c_c___h_s_i___config.html',1,'HSI Config'],['../group___r_c_c___l_s_e___config.html',1,'LSE Config'],['../group___r_c_c___l_s_i___config.html',1,'LSI Config'],['../group___r_c_c___p_l_l___config.html',1,'PLL Config'],['../group___r_c_c_ex___m_c_ox___clock___config.html',1,'RCC Extended MCOx Clock Config']]],
  ['configuration_76',['Configuration',['../group___g_p_i_o_ex___e_v_e_n_t_o_u_t.html',1,'EVENTOUT Cortex Configuration'],['../group___r_c_c___h_s_e___configuration.html',1,'HSE Configuration'],['../group___r_c_c_ex___h_s_e___configuration.html',1,'HSE Configuration'],['../group___r_c_c___h_s_i___configuration.html',1,'HSI Configuration'],['../group___r_c_c___l_s_e___configuration.html',1,'LSE Configuration'],['../group___r_c_c___l_s_i___configuration.html',1,'LSI Configuration'],['../group___r_c_c_ex___peripheral___configuration.html',1,'Peripheral Configuration'],['../group___r_c_c___p_l_l___configuration.html',1,'PLL Configuration'],['../group___r_c_c___r_t_c___clock___configuration.html',1,'RCC RTC Clock Configuration']]],
  ['configuration_77',['VL53L0A1 static configuration',['../group___v_l53_l0_a1__config.html',1,'']]],
  ['configuration_20definition_78',['I2C Interrupt configuration definition',['../group___i2_c___interrupt__configuration__definition.html',1,'']]],
  ['configuration_20functions_79',['Configuration functions',['../group___e_x_t_i___exported___functions___group1.html',1,'']]],
  ['configuration_20structure_80',['Configuration structure',['../group___a_c_c_e_l_e_r_o___configuration__structure.html',1,'Accelerometer Configuration structure'],['../group___g_y_r_o___config__structure.html',1,'Gyroscope Configuration structure'],['../group___i_d_d___config__structure.html',1,'IDD Configuration structure'],['../group___m_a_g_n_e_t_o___config__structure.html',1,'Magnetometer Configuration structure'],['../group___t_s_e_n_s_o_r___config__structure.html',1,'Temperature Sensor Configuration structure']]],
  ['configuration_5fsection_5ffor_5fcmsis_81',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['constants_82',['Constants',['../group___a_d_c___exported___constants.html',1,'ADC Exported Constants'],['../group___a_d_c___private___constants.html',1,'ADC Private Constants'],['../group___a_d_c_ex___exported___constants.html',1,'ADCEx Exported Constants'],['../group___a_d_c_ex___private___constants.html',1,'ADCEx Private Constants'],['../group___s_t_m32_f1_x_x___n_u_c_l_e_o___b_u_s.html',1,'BUS Constants'],['../group___s_t_m32_f1_x_x___n_u_c_l_e_o___b_u_t_t_o_n.html',1,'BUTTON Constants'],['../group___c_o_r_t_e_x___exported___constants.html',1,'CORTEX Exported Constants'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'CORTEX Exported Constants'],['../group___d_m_a___exported___constants.html',1,'DMA Exported Constants'],['../group___s_t_m32_f1_x_x___n_u_c_l_e_o___exported___constants.html',1,'Exported Constants'],['../group___e_x_t_i___exported___constants.html',1,'EXTI Exported Constants'],['../group___e_x_t_i___private___constants.html',1,'EXTI Private Constants'],['../group___f_l_a_s_h_ex___constants.html',1,'FLASH Constants'],['../group___f_l_a_s_h___exported___constants.html',1,'FLASH Exported Constants'],['../group___f_l_a_s_h_ex___exported___constants.html',1,'FLASHEx Exported Constants'],['../group___g_p_i_o___exported___constants.html',1,'GPIO Exported Constants'],['../group___g_p_i_o___private___constants.html',1,'GPIO Private Constants'],['../group___g_p_i_o_ex___exported___constants.html',1,'GPIOEx Exported Constants'],['../group___h_a_l___exported___constants.html',1,'HAL Exported Constants'],['../group___h_a_l___private___constants.html',1,'HAL Private Constants'],['../group___i2_c___exported___constants.html',1,'I2C Exported Constants'],['../group___i2_c___private___constants.html',1,'I2C Private Constants']]],
  ['constants_83',['IRDA Exported constants',['../group___i_r_d_a___exported___constants.html',1,'']]],
  ['constants_84',['Constants',['../group___i_r_d_a___private___constants.html',1,'IRDA Private Constants'],['../group___i_w_d_g___exported___constants.html',1,'IWDG Exported Constants'],['../group___i_w_d_g___private___constants.html',1,'IWDG Private Constants'],['../group___s_t_m32_f1_x_x___n_u_c_l_e_o___l_e_d.html',1,'LED Constants'],['../group___f_l_a_s_h_ex___option_byte___constants.html',1,'Option Byte Constants']]],
  ['constants_85',['constants',['../group___c_o_m_p_o_n_e_n_t___public___constants.html',1,'Public constants'],['../group___h_t_s221___public___constants.html',1,'Public constants'],['../group___l_i_s3_m_d_l___public___constants.html',1,'Public constants'],['../group___l_p_s22_h_b___public___constants.html',1,'Public constants'],['../group___l_p_s25_h_b___public___constants.html',1,'Public constants'],['../group___l_s_m6_d_s0___public___constants.html',1,'Public constants'],['../group___l_s_m6_d_s3___public___constants.html',1,'Public constants'],['../group___x___n_u_c_l_e_o___i_k_s01_a1___i_o___public___constants.html',1,'Public constants']]],
  ['constants_86',['Constants',['../group___p_w_r___exported___constants.html',1,'PWR Exported Constants'],['../group___r_c_c___exported___constants.html',1,'RCC Exported Constants'],['../group___r_c_c_ex___exported___constants.html',1,'RCCEx Exported Constants'],['../group___r_t_c___exported___constants.html',1,'RTC Exported Constants'],['../group___r_t_c_ex___exported___constants.html',1,'RTCEx Exported Constants']]],
  ['constants_87',['SMARTCARD Exported constants',['../group___s_m_a_r_t_c_a_r_d___exported___constants.html',1,'']]],
  ['constants_88',['Constants',['../group___s_m_a_r_t_c_a_r_d___private___constants.html',1,'SMARTCARD Private Constants'],['../group___s_p_i___exported___constants.html',1,'SPI Exported Constants'],['../group___s_p_i___private___constants.html',1,'SPI Private Constants'],['../group___t_i_m___exported___constants.html',1,'TIM Exported Constants'],['../group___t_i_m_ex___exported___constants.html',1,'TIM Extended Exported Constants'],['../group___t_i_m___private___constants.html',1,'TIM Private Constants']]],
  ['constants_89',['UART Exported constants',['../group___u_a_r_t___exported___constants.html',1,'']]],
  ['constants_90',['Constants',['../group___u_a_r_t___private___constants.html',1,'UART Private Constants'],['../group___u_s_a_r_t___exported___constants.html',1,'USART Exported Constants'],['../group___u_s_a_r_t___private___constants.html',1,'USART Private Constants'],['../group___u_t_i_l_s___l_l___exported___constants.html',1,'UTILS Exported Constants'],['../group___u_t_i_l_s___l_l___private___constants.html',1,'UTILS Private Constants'],['../group___w_w_d_g___exported___constants.html',1,'WWDG Exported Constants']]],
  ['control_91',['Control',['../group___p_i_d.html',1,'PID Motor Control'],['../group___u_a_r_t___hardware___flow___control.html',1,'UART Hardware Flow Control']]],
  ['control_20block_20scb_92',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['control_20functions_93',['Control functions',['../group___t_i_m_ex___exported___functions___group5.html',1,'Extended Peripheral Control functions'],['../group___p_w_r___exported___functions___group2.html',1,'Peripheral Control functions'],['../group___t_i_m___exported___functions___group8.html',1,'TIM Peripheral Control functions']]],
  ['control_20registers_94',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['controller_20functions_95',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['controller_20nvic_96',['Nested Vectored Interrupt Controller (NVIC)',['../group___c_m_s_i_s___n_v_i_c.html',1,'']]],
  ['controls_20not_20in_20scb_20scnscb_97',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['conv_20verification_98',['conv verification',['../group___a_d_c__regular__nb__conv__verification.html',1,'ADC regular nb conv verification'],['../group___a_d_c_ex__injected__nb__conv__verification.html',1,'ADCEx injected nb conv verification']]],
  ['conversion_20cycles_99',['ADC conversion cycles',['../group___a_d_c__conversion__cycles.html',1,'']]],
  ['conversion_20group_100',['ADC conversion group',['../group___a_d_c__conversion__group.html',1,'']]],
  ['core_20debug_20registers_20coredebug_101',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_102',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20instruction_20interface_103',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['core_20register_20access_20functions_104',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20register_20bit_20field_20macros_105',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['coredebug_106',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['cortex_107',['CORTEX',['../group___c_o_r_t_e_x___l_l.html',1,'CORTEX'],['../group___c_o_r_t_e_x.html',1,'CORTEX']]],
  ['cortex_20_5fsystick_20clock_20source_108',['CORTEX _SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cortex_20aliased_20defines_20maintained_20for_20legacy_20purpose_109',['HAL CORTEX Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_o_r_t_e_x___aliased___defines.html',1,'']]],
  ['cortex_20configuration_110',['EVENTOUT Cortex Configuration',['../group___g_p_i_o_ex___e_v_e_n_t_o_u_t.html',1,'']]],
  ['cortex_20exported_20constants_111',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'CORTEX Exported Constants'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'CORTEX Exported Constants']]],
  ['cortex_20exported_20functions_112',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___l_l___exported___functions.html',1,'']]],
  ['cortex_20exported_20types_113',['Cortex Exported Types',['../group___c_o_r_t_e_x___exported___types.html',1,'']]],
  ['cortex_20preemption_20priority_20group_114',['CORTEX Preemption Priority Group',['../group___c_o_r_t_e_x___preemption___priority___group.html',1,'']]],
  ['cortex_20private_20macros_115',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_5fexported_5ffunctions_116',['CORTEX_Exported_Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup1_117',['CORTEX_Exported_Functions_Group1',['../group___c_o_r_t_e_x___exported___functions___group1.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup2_118',['CORTEX_Exported_Functions_Group2',['../group___c_o_r_t_e_x___exported___functions___group2.html',1,'']]],
  ['counter_20mode_119',['TIM Counter Mode',['../group___t_i_m___counter___mode.html',1,'']]],
  ['crc_120',['CRC',['../group___c_r_c.html',1,'']]],
  ['crc_20aliased_20defines_20maintained_20for_20legacy_20purpose_121',['HAL CRC Aliased Defines maintained for legacy purpose',['../group___h_a_l___c_r_c___aliased___defines.html',1,'']]],
  ['crc_20calculation_122',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['crc_20exported_20macros_123',['CRC Exported Macros',['../group___c_r_c___exported___macros.html',1,'']]],
  ['crc_20exported_20types_124',['CRC Exported Types',['../group___c_r_c___exported___types.html',1,'']]],
  ['crc_5fexported_5ffunctions_125',['CRC_Exported_Functions',['../group___c_r_c___exported___functions.html',1,'']]],
  ['crc_5fexported_5ffunctions_5fgroup1_126',['CRC_Exported_Functions_Group1',['../group___c_r_c___exported___functions___group1.html',1,'']]],
  ['crc_5fexported_5ffunctions_5fgroup2_127',['CRC_Exported_Functions_Group2',['../group___c_r_c___exported___functions___group2.html',1,'']]],
  ['crc_5fexported_5ffunctions_5fgroup3_128',['CRC_Exported_Functions_Group3',['../group___c_r_c___exported___functions___group3.html',1,'']]],
  ['cryp_20aliased_20defines_20maintained_20for_20legacy_20purpose_129',['HAL CRYP Aliased Defines maintained for legacy purpose',['../group___h_a_l___a_e_s___aliased___defines.html',1,'']]],
  ['cryp_20aliased_20functions_20maintained_20for_20legacy_20purpose_130',['HAL CRYP Aliased Functions maintained for legacy purpose',['../group___h_a_l___c_r_y_p___aliased___functions.html',1,'']]],
  ['cryp_20aliased_20macros_20maintained_20for_20legacy_20purpose_131',['HAL CRYP Aliased Macros maintained for legacy purpose',['../group___h_a_l___a_e_s___aliased___macros.html',1,'']]],
  ['current_20status_20of_20the_20device_132',['Defines the current status of the device',['../group___v_l53_l0_x__define___state__group.html',1,'']]],
  ['cut1_201_20device_20specific_20defines_133',['VL53L0X cut1.1 Device Specific Defines',['../group___v_l53_l0_x___dev_spec_defines__group.html',1,'']]],
  ['cut1_201_20function_20definition_134',['VL53L0X cut1.1 Function Definition',['../group___v_l53_l0_x__cut11__group.html',1,'']]],
  ['cycle_135',['FLASH Half Cycle',['../group___f_l_a_s_h___half___cycle.html',1,'']]],
  ['cycle_20in_20fast_20mode_136',['I2C duty cycle in fast mode',['../group___i2_c__duty__cycle__in__fast__mode.html',1,'']]],
  ['cycles_137',['ADC conversion cycles',['../group___a_d_c__conversion__cycles.html',1,'']]]
];
