var searchData=
[
  ['o_20function_0',['Basic I/O function',['../group___basic___i_o__function___w5100.html',1,'']]],
  ['o_20functions_1',['WIZCHIP I/O functions',['../group___w_i_z_c_h_i_p___i_o___functions___w5100.html',1,'']]],
  ['of_20available_20power_20modes_2',['List of available Power Modes',['../group___v_l53_l0_x__define___power_modes__group.html',1,'']]],
  ['of_20prediv_20for_201sec_20timebase_3',['Automatic calculation of prediv for 1sec timebase',['../group___r_t_c___automatic___prediv__1___second.html',1,'']]],
  ['of_20stop_20bits_4',['of Stop Bits',['../group___s_m_a_r_t_c_a_r_d___stop___bits.html',1,'SMARTCARD Number of Stop Bits'],['../group___u_a_r_t___stop___bits.html',1,'UART Number of Stop Bits'],['../group___u_s_a_r_t___stop___bits.html',1,'USART Number of Stop Bits']]],
  ['of_20the_20device_5',['Defines the current status of the device',['../group___v_l53_l0_x__define___state__group.html',1,'']]],
  ['offsets_6',['Register offsets',['../group___r_c_c___register___offset.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_7',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_8',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['on_20selected_20full_20scale_9',['on selected full scale',['../group___l_s_m6_d_s0___a_c_c___s_e_n_s_i_t_i_v_i_t_y.html',1,'Accelero sensitivity values based on selected full scale'],['../group___l_s_m6_d_s3___a_c_c___s_e_n_s_i_t_i_v_i_t_y.html',1,'Accelero sensitivity values based on selected full scale'],['../group___l_s_m6_d_s0___g_y_r_o___s_e_n_s_i_t_i_v_i_t_y.html',1,'Gyro sensitivity values based on selected full scale'],['../group___l_s_m6_d_s3___g_y_r_o___s_e_n_s_i_t_i_v_i_t_y.html',1,'Gyro sensitivity values based on selected full scale'],['../group___l_i_s3_m_d_l___s_e_n_s_i_t_i_v_i_t_y.html',1,'Sensitivity values based on selected full scale']]],
  ['on_20the_20tamper_20pin_10',['Output source to output on the Tamper pin',['../group___r_t_c__output__source__to__output__on__the___tamper__pin.html',1,'']]],
  ['one_20pulse_20functions_11',['One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group___t_i_m___exported___functions___group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_12',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_13',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_14',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operation_20functions_15',['operation functions',['../group___e_x_t_i___exported___functions___group2.html',1,'IO operation functions'],['../group___i_w_d_g___exported___functions___group2.html',1,'IO operation functions']]],
  ['option_20byte_20constants_16',['Option Byte Constants',['../group___f_l_a_s_h_ex___option_byte___constants.html',1,'']]],
  ['option_20byte_20data_20address_17',['Option Byte Data Address',['../group___f_l_a_s_h_ex___o_b___data___address.html',1,'']]],
  ['option_20byte_20iwatchdog_18',['Option Byte IWatchdog',['../group___f_l_a_s_h_ex___o_b___i_watchdog.html',1,'']]],
  ['option_20byte_20nrst_20stdby_19',['Option Byte nRST STDBY',['../group___f_l_a_s_h_ex___o_b__n_r_s_t___s_t_d_b_y.html',1,'']]],
  ['option_20byte_20nrst_20stop_20',['Option Byte nRST STOP',['../group___f_l_a_s_h_ex___o_b__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20byte_20read_20protection_21',['Option Byte Read Protection',['../group___f_l_a_s_h_ex___o_b___read___protection.html',1,'']]],
  ['option_20byte_20wrp_20state_22',['Option Byte WRP State',['../group___f_l_a_s_h_ex___o_b___w_r_p___state.html',1,'']]],
  ['option_20bytes_20type_23',['Option Bytes Type',['../group___f_l_a_s_h_ex___o_b___type.html',1,'']]],
  ['option_20bytes_20write_20protection_24',['Option Bytes Write Protection',['../group___f_l_a_s_h_ex___o_b___write___protection.html',1,'']]],
  ['oscillator_20type_25',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_26',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_27',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_28',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_29',['Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_30',['Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_31',['Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_32',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20enable_33',['TIM Automatic Output Enable',['../group___t_i_m___a_o_e___bit___set___reset.html',1,'']]],
  ['output_20fast_20state_34',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['output_20on_20the_20tamper_20pin_35',['Output source to output on the Tamper pin',['../group___r_t_c__output__source__to__output__on__the___tamper__pin.html',1,'']]],
  ['output_20source_20to_20output_20on_20the_20tamper_20pin_36',['Output source to output on the Tamper pin',['../group___r_t_c__output__source__to__output__on__the___tamper__pin.html',1,'']]],
  ['over_20sampling_37',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]]
];
